/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/adjustments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postAdjustment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/items/{itemId}/on-hand": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["onHand"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/reconciliation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["reconciliation_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ledger/fiscal-years/{yearCode}/periods/{periodNo}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["closePeriod"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ledger/fiscal-years/{yearCode}/periods/{periodNo}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reopenPeriod"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ledger/journal-entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ledger/trial-balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["trialBalance_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/manufacturing/boms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listBoms"];
        put?: never;
        post: operations["createBom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/manufacturing/boms/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBom"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/manufacturing/reorder-report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["reorderReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/manufacturing/work-orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listWorkOrders"];
        put?: never;
        post: operations["createWorkOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/manufacturing/work-orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getWorkOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/manufacturing/work-orders/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/manufacturing/work-orders/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["complete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/manufacturing/work-orders/{id}/issue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["issue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/manufacturing/work-orders/{id}/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["release"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/masterdata/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listItems"];
        put?: never;
        post: operations["createItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/masterdata/items/by-sku": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getItemBySku"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/masterdata/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/masterdata/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listLocations"];
        put?: never;
        post: operations["createLocation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/masterdata/locations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLocation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/masterdata/partners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPartners"];
        put?: never;
        post: operations["createPartner"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/masterdata/partners/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPartner"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/masterdata/warehouses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listWarehouses"];
        put?: never;
        post: operations["createWarehouse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPayments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["payIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["payOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPayment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/purchasing/ap-aging": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["apAging"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/purchasing/goods-receipts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listReceipts"];
        put?: never;
        post: operations["receive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/purchasing/goods-receipts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReceipt"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/purchasing/purchase-orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listOrders_1"];
        put?: never;
        post: operations["createOrder_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/purchasing/purchase-orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOrder_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/purchasing/purchase-orders/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirm_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/purchasing/vendor-bills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listBills"];
        put?: never;
        post: operations["postBill"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/purchasing/vendor-bills/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBill"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reporting/balance-sheet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["balanceSheet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reporting/general-ledger/{accountCode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["generalLedger"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reporting/income-statement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["incomeStatement"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reporting/reconciliation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["reconciliation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reporting/trial-balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["trialBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales/ar-aging": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["arAging"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales/customer-returns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listReturns"];
        put?: never;
        post: operations["postReturn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales/customer-returns/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReturn"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDeliveries"];
        put?: never;
        post: operations["deliver"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales/deliveries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDelivery"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales/sales-invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listInvoices"];
        put?: never;
        post: operations["postInvoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales/sales-invoices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getInvoice"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales/sales-orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listOrders"];
        put?: never;
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales/sales-orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales/sales-orders/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccountSubledgerValue: {
            accountCode?: string;
            subledgerValue?: string;
        };
        AdjustmentResponse: {
            adjustmentNumber?: string;
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            itemId?: number;
            /** Format: int64 */
            journalEntryId?: number;
            /** Format: int64 */
            locationId?: number;
            /** Format: uuid */
            movementGroupId?: string;
            /** Format: date-time */
            postedAt?: string;
            qtyDelta?: string;
            reason?: string;
            status?: string;
            unitCost?: string;
        };
        AllocationLine: {
            amount?: string;
            /** Format: int64 */
            billId?: number;
        };
        AllocationView: {
            amount?: string;
            /** Format: int64 */
            documentId?: number;
            /** Format: int64 */
            id?: number;
        };
        ApAgingReport: {
            current?: string;
            days1to30?: string;
            days31to60?: string;
            days61to90?: string;
            days90plus?: string;
            total?: string;
        };
        ArAgingReport: {
            current?: string;
            days1to30?: string;
            days31to60?: string;
            days61to90?: string;
            days90plus?: string;
            total?: string;
        };
        BalanceSheet: {
            /** Format: date */
            asOf?: string;
            assets?: components["schemas"]["StatementLine"][];
            balanced?: boolean;
            equity?: components["schemas"]["StatementLine"][];
            liabilities?: components["schemas"]["StatementLine"][];
            netIncome?: string;
            totalAssets?: string;
            totalEquity?: string;
            totalLiabilities?: string;
        };
        BillLine: {
            /** Format: int64 */
            poLineId?: number;
            qty?: string;
            unitPrice?: string;
        };
        BillLineView: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            itemId?: number;
            lineNet?: string;
            lineVat?: string;
            matchStatus?: string;
            /** Format: int64 */
            poLineId?: number;
            qty?: string;
            unitPrice?: string;
        };
        BomComponentView: {
            /** Format: int64 */
            componentItemId?: number;
            /** Format: int64 */
            id?: number;
            /** Format: int32 */
            lineNo?: number;
            qtyPer?: string;
            scrapPct?: string;
        };
        BomResponse: {
            components?: components["schemas"]["BomComponentView"][];
            /** Format: int64 */
            id?: number;
            outputQty?: string;
            /** Format: int64 */
            parentItemId?: number;
            status?: string;
            /** Format: int32 */
            version?: number;
        };
        CancelRequest: {
            /** Format: date */
            postingDate?: string;
            /** Format: int64 */
            stockLocationId?: number;
        };
        ClearingBalance: {
            accountCode?: string;
            balance?: string;
            cleared?: boolean;
            name?: string;
        };
        CompleteRequest: {
            /** Format: date */
            postingDate?: string;
            qtyProduced?: string;
            /** Format: int64 */
            stockLocationId?: number;
        };
        CreateAdjustmentRequest: {
            /** Format: int64 */
            itemId?: number;
            /** Format: int64 */
            locationId?: number;
            /** Format: date */
            postingDate?: string;
            qtyDelta?: string;
            reason?: string;
            unitCost?: string;
        };
        CreateBillRequest: {
            lines?: components["schemas"]["BillLine"][];
            /** Format: date */
            postingDate?: string;
            /** Format: int64 */
            purchaseOrderId?: number;
            taxRateCode?: string;
        };
        CreateBomComponent: {
            /** Format: int64 */
            componentItemId?: number;
            qtyPer?: string;
            scrapPct?: string;
        };
        CreateBomRequest: {
            components?: components["schemas"]["CreateBomComponent"][];
            outputQty?: string;
            /** Format: int64 */
            parentItemId?: number;
        };
        CreateDeliveryRequest: {
            lines?: components["schemas"]["DeliveryLine"][];
            /** Format: date */
            postingDate?: string;
            /** Format: int64 */
            salesOrderId?: number;
            /** Format: int64 */
            stockLocationId?: number;
        };
        CreateGrnRequest: {
            lines?: components["schemas"]["ReceiptLine"][];
            /** Format: date */
            postingDate?: string;
            /** Format: int64 */
            purchaseOrderId?: number;
            /** Format: int64 */
            stockLocationId?: number;
        };
        CreateInvoiceRequest: {
            lines?: components["schemas"]["InvoiceLine"][];
            /** Format: date */
            postingDate?: string;
            /** Format: int64 */
            salesOrderId?: number;
            taxRateCode?: string;
        };
        CreateItemRequest: {
            /** @enum {string} */
            itemType?: "RAW" | "WIP" | "FINISHED" | "SERVICE";
            name?: string;
            reorderPoint?: string;
            reorderQty?: string;
            sku?: string;
            standardCost?: string;
            stocked?: boolean;
            uom?: string;
        };
        CreateLocationRequest: {
            code?: string;
            /** @enum {string} */
            locationType?: "STOCK" | "RECEIVING" | "SHIPPING" | "PRODUCTION_WIP" | "SCRAP" | "VENDOR" | "CUSTOMER" | "INVENTORY_LOSS";
            /** Format: int64 */
            warehouseId?: number;
        };
        CreatePartnerRequest: {
            apAccountCode?: string;
            arAccountCode?: string;
            code?: string;
            customer?: boolean;
            name?: string;
            /** Format: int32 */
            paymentTermsDays?: number;
            taxId?: string;
            vendor?: boolean;
        };
        CreatePoLine: {
            /** Format: int64 */
            itemId?: number;
            qtyOrdered?: string;
            unitPrice?: string;
        };
        CreatePoRequest: {
            lines?: components["schemas"]["CreatePoLine"][];
            /** Format: date */
            orderDate?: string;
            /** Format: int64 */
            partnerId?: number;
        };
        CreateReturnRequest: {
            /** Format: date */
            postingDate?: string;
            /** Format: int64 */
            salesInvoiceId?: number;
            /** Format: int64 */
            stockLocationId?: number;
        };
        CreateSoLine: {
            /** Format: int64 */
            itemId?: number;
            qtyOrdered?: string;
            unitPrice?: string;
        };
        CreateSoRequest: {
            lines?: components["schemas"]["CreateSoLine"][];
            /** Format: date */
            orderDate?: string;
            /** Format: int64 */
            partnerId?: number;
        };
        CreateWarehouseRequest: {
            code?: string;
            name?: string;
        };
        CreateWorkOrderRequest: {
            /** Format: int64 */
            bomId?: number;
            /** Format: int64 */
            itemId?: number;
            qtyToProduce?: string;
        };
        CurrentUserResponse: {
            roles?: string[];
            username?: string;
        };
        CustomerReturnLineView: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            itemId?: number;
            lineCogs?: string;
            lineNet?: string;
            lineVat?: string;
            /** Format: uuid */
            movementGroupId?: string;
            qty?: string;
            /** Format: int64 */
            soLineId?: number;
            /** Format: int64 */
            stockJournalEntryId?: number;
        };
        CustomerReturnResponse: {
            cogsAmount?: string;
            /** Format: int64 */
            creditNoteJournalEntryId?: number;
            goodsAmount?: string;
            grossAmount?: string;
            /** Format: int64 */
            id?: number;
            lines?: components["schemas"]["CustomerReturnLineView"][];
            /** Format: int64 */
            partnerId?: number;
            /** Format: date-time */
            postedAt?: string;
            /** Format: date */
            postingDate?: string;
            returnNumber?: string;
            /** Format: int64 */
            salesInvoiceId?: number;
            /** Format: int64 */
            salesOrderId?: number;
            status?: string;
            vatAmount?: string;
        };
        DeliveryLine: {
            qty?: string;
            /** Format: int64 */
            soLineId?: number;
        };
        DeliveryLineView: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            itemId?: number;
            /** Format: int64 */
            journalEntryId?: number;
            /** Format: uuid */
            movementGroupId?: string;
            qtyShipped?: string;
            /** Format: int64 */
            soLineId?: number;
            unitCost?: string;
        };
        DeliveryResponse: {
            deliveryNumber?: string;
            /** Format: int64 */
            id?: number;
            lines?: components["schemas"]["DeliveryLineView"][];
            /** Format: date-time */
            postedAt?: string;
            /** Format: date */
            postingDate?: string;
            /** Format: int64 */
            salesOrderId?: number;
            status?: string;
        };
        FiscalPeriodResponse: {
            /** Format: date */
            endDate?: string;
            /** Format: int32 */
            periodNo?: number;
            /** Format: date */
            startDate?: string;
            status?: string;
            yearCode?: string;
        };
        GoodsReceiptResponse: {
            grnNumber?: string;
            /** Format: int64 */
            id?: number;
            lines?: components["schemas"]["GrnLineView"][];
            /** Format: date-time */
            postedAt?: string;
            /** Format: date */
            postingDate?: string;
            /** Format: int64 */
            purchaseOrderId?: number;
            status?: string;
        };
        GrnLineView: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            itemId?: number;
            /** Format: int64 */
            journalEntryId?: number;
            /** Format: uuid */
            movementGroupId?: string;
            /** Format: int64 */
            poLineId?: number;
            qtyReceived?: string;
            unitCost?: string;
        };
        IncomeStatement: {
            /** Format: date */
            asOf?: string;
            expenses?: components["schemas"]["StatementLine"][];
            netIncome?: string;
            revenue?: components["schemas"]["StatementLine"][];
            totalExpenses?: string;
            totalRevenue?: string;
        };
        InvoiceLine: {
            qty?: string;
            /** Format: int64 */
            soLineId?: number;
            unitPrice?: string;
        };
        InvoiceLineView: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            itemId?: number;
            lineCogs?: string;
            lineNet?: string;
            lineVat?: string;
            qty?: string;
            /** Format: int64 */
            soLineId?: number;
            unitPrice?: string;
        };
        IssueRequest: {
            /** Format: date */
            postingDate?: string;
            /** Format: int64 */
            stockLocationId?: number;
        };
        ItemResponse: {
            /** Format: int64 */
            id?: number;
            /** @enum {string} */
            itemType?: "RAW" | "WIP" | "FINISHED" | "SERVICE";
            name?: string;
            reorderPoint?: string;
            reorderQty?: string;
            sku?: string;
            standardCost?: string;
            stocked?: boolean;
            uom?: string;
        };
        ItemStock: {
            avgUnitCost?: string;
            /** Format: int64 */
            itemId?: number;
            onHandQty?: string;
            sku?: string;
            totalValue?: string;
        };
        JournalEntryLine: {
            accountCode?: string;
            credit?: string;
            debit?: string;
            memo?: string;
            /** Format: int64 */
            partnerId?: number;
        };
        JournalEntryRequest: {
            currencyCode?: string;
            journalCode?: string;
            lines?: components["schemas"]["JournalEntryLine"][];
            memo?: string;
            /** Format: date */
            postingDate?: string;
            sourceDocId?: string;
            sourceDocType?: string;
            sourceEvent?: string;
        };
        JournalEntryResponse: {
            currencyCode?: string;
            /** Format: int64 */
            entryNo?: number;
            /** Format: int64 */
            id?: number;
            /** Format: date */
            postingDate?: string;
            status?: string;
            totalCredit?: string;
            totalDebit?: string;
        };
        LedgerLineView: {
            accountCode?: string;
            credit?: string;
            debit?: string;
            /** Format: int64 */
            entryId?: number;
            /** Format: int64 */
            entryNo?: number;
            memo?: string;
            /** Format: date */
            postingDate?: string;
            sourceDocId?: string;
            sourceDocType?: string;
        };
        LocationResponse: {
            active?: boolean;
            code?: string;
            /** Format: int64 */
            id?: number;
            /** @enum {string} */
            locationType?: "STOCK" | "RECEIVING" | "SHIPPING" | "PRODUCTION_WIP" | "SCRAP" | "VENDOR" | "CUSTOMER" | "INVENTORY_LOSS";
            /** Format: int64 */
            warehouseId?: number;
        };
        LoginRequest: {
            password?: string;
            username?: string;
        };
        PartnerResponse: {
            active?: boolean;
            apAccountCode?: string;
            arAccountCode?: string;
            code?: string;
            customer?: boolean;
            /** Format: int64 */
            id?: number;
            name?: string;
            /** Format: int32 */
            paymentTermsDays?: number;
            taxId?: string;
            vendor?: boolean;
        };
        PayInRequest: {
            allocations?: components["schemas"]["ReceiptAllocationLine"][];
            amount?: string;
            /** Format: int64 */
            partnerId?: number;
            /** Format: date */
            postingDate?: string;
        };
        PayOutRequest: {
            allocations?: components["schemas"]["AllocationLine"][];
            amount?: string;
            /** Format: int64 */
            partnerId?: number;
            /** Format: date */
            postingDate?: string;
        };
        PaymentResponse: {
            allocations?: components["schemas"]["AllocationView"][];
            amount?: string;
            direction?: string;
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            journalEntryId?: number;
            /** Format: int64 */
            partnerId?: number;
            payNumber?: string;
            /** Format: date-time */
            postedAt?: string;
            /** Format: date */
            postingDate?: string;
            status?: string;
        };
        PoLineView: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            itemId?: number;
            /** Format: int32 */
            lineNo?: number;
            qtyBilled?: string;
            qtyOrdered?: string;
            qtyReceived?: string;
            unitPrice?: string;
        };
        PurchaseOrderResponse: {
            /** Format: int64 */
            id?: number;
            lines?: components["schemas"]["PoLineView"][];
            /** Format: date */
            orderDate?: string;
            /** Format: int64 */
            partnerId?: number;
            poNumber?: string;
            status?: string;
        };
        ReceiptAllocationLine: {
            amount?: string;
            /** Format: int64 */
            invoiceId?: number;
        };
        ReceiptLine: {
            /** Format: int64 */
            poLineId?: number;
            qty?: string;
        };
        ReconciliationReport: {
            /** Format: date */
            asOf?: string;
            clearingAccounts?: components["schemas"]["ClearingBalance"][];
            healthy?: boolean;
            subledgerChecks?: components["schemas"]["SubledgerCheck"][];
            trialBalanceBalanced?: boolean;
        };
        ReorderItem: {
            /** Format: int64 */
            itemId?: number;
            name?: string;
            onHandQty?: string;
            reorderPoint?: string;
            reorderQty?: string;
            sku?: string;
        };
        ReorderReport: {
            items?: components["schemas"]["ReorderItem"][];
        };
        SalesInvoiceResponse: {
            amountReceived?: string;
            cogsAmount?: string;
            goodsAmount?: string;
            grossAmount?: string;
            /** Format: int64 */
            id?: number;
            invoiceNumber?: string;
            /** Format: int64 */
            journalEntryId?: number;
            lines?: components["schemas"]["InvoiceLineView"][];
            openBalance?: string;
            /** Format: int64 */
            partnerId?: number;
            /** Format: date-time */
            postedAt?: string;
            /** Format: date */
            postingDate?: string;
            /** Format: int64 */
            salesOrderId?: number;
            status?: string;
            vatAmount?: string;
        };
        SalesOrderResponse: {
            /** Format: int64 */
            id?: number;
            lines?: components["schemas"]["SoLineView"][];
            /** Format: date */
            orderDate?: string;
            /** Format: int64 */
            partnerId?: number;
            soNumber?: string;
            status?: string;
        };
        SoLineView: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            itemId?: number;
            /** Format: int32 */
            lineNo?: number;
            qtyInvoiced?: string;
            qtyOrdered?: string;
            qtyShipped?: string;
            unitPrice?: string;
        };
        StatementLine: {
            amount?: string;
            code?: string;
            name?: string;
        };
        SubledgerCheck: {
            accountCode?: string;
            glControl?: string;
            label?: string;
            reconciled?: boolean;
            subledger?: string;
        };
        TokenResponse: {
            accessToken?: string;
            roles?: string[];
            username?: string;
        };
        TrialBalance: {
            /** Format: date */
            asOf?: string;
            balanced?: boolean;
            lines?: components["schemas"]["TrialBalanceRow"][];
            totalCredit?: string;
            totalDebit?: string;
        };
        TrialBalanceLine: {
            accountClass?: string;
            code?: string;
            name?: string;
            totalCredit?: string;
            totalDebit?: string;
        };
        TrialBalanceReport: {
            balanced?: boolean;
            lines?: components["schemas"]["TrialBalanceLine"][];
            totalCredit?: string;
            totalDebit?: string;
        };
        TrialBalanceRow: {
            accountClass?: string;
            code?: string;
            credit?: string;
            debit?: string;
            name?: string;
        };
        VendorBillResponse: {
            amountPaid?: string;
            billNumber?: string;
            goodsAmount?: string;
            grossAmount?: string;
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            journalEntryId?: number;
            lines?: components["schemas"]["BillLineView"][];
            openBalance?: string;
            /** Format: int64 */
            partnerId?: number;
            /** Format: date-time */
            postedAt?: string;
            /** Format: date */
            postingDate?: string;
            /** Format: int64 */
            purchaseOrderId?: number;
            status?: string;
            vatAmount?: string;
        };
        WarehouseResponse: {
            active?: boolean;
            code?: string;
            /** Format: int64 */
            id?: number;
            name?: string;
        };
        WorkOrderComponentView: {
            /** Format: int64 */
            componentItemId?: number;
            consumedQty?: string;
            consumedValue?: string;
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            journalEntryId?: number;
            /** Format: int32 */
            lineNo?: number;
            /** Format: uuid */
            movementGroupId?: string;
            plannedQty?: string;
        };
        WorkOrderResponse: {
            /** Format: int64 */
            bomId?: number;
            components?: components["schemas"]["WorkOrderComponentView"][];
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            itemId?: number;
            qtyProduced?: string;
            qtyToProduce?: string;
            status?: string;
            totalComponentCost?: string;
            /** Format: int64 */
            wipLocationId?: number;
            woNumber?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CurrentUserResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    postAdjustment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAdjustmentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdjustmentResponse"];
                };
            };
        };
    };
    onHand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ItemStock"];
                };
            };
        };
    };
    reconciliation_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountSubledgerValue"][];
                };
            };
        };
    };
    closePeriod: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                yearCode: string;
                periodNo: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FiscalPeriodResponse"];
                };
            };
        };
    };
    reopenPeriod: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                yearCode: string;
                periodNo: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FiscalPeriodResponse"];
                };
            };
        };
    };
    post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JournalEntryRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["JournalEntryResponse"];
                };
            };
        };
    };
    trialBalance_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TrialBalanceReport"];
                };
            };
        };
    };
    listBoms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BomResponse"][];
                };
            };
        };
    };
    createBom: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBomRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BomResponse"];
                };
            };
        };
    };
    getBom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BomResponse"];
                };
            };
        };
    };
    reorderReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReorderReport"];
                };
            };
        };
    };
    listWorkOrders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkOrderResponse"][];
                };
            };
        };
    };
    createWorkOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkOrderRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkOrderResponse"];
                };
            };
        };
    };
    getWorkOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkOrderResponse"];
                };
            };
        };
    };
    cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkOrderResponse"];
                };
            };
        };
    };
    complete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkOrderResponse"];
                };
            };
        };
    };
    issue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkOrderResponse"];
                };
            };
        };
    };
    release: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkOrderResponse"];
                };
            };
        };
    };
    listItems: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ItemResponse"][];
                };
            };
        };
    };
    createItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateItemRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ItemResponse"];
                };
            };
        };
    };
    getItemBySku: {
        parameters: {
            query: {
                sku: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ItemResponse"];
                };
            };
        };
    };
    getItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ItemResponse"];
                };
            };
        };
    };
    listLocations: {
        parameters: {
            query?: {
                warehouseId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LocationResponse"][];
                };
            };
        };
    };
    createLocation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLocationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LocationResponse"];
                };
            };
        };
    };
    getLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LocationResponse"];
                };
            };
        };
    };
    listPartners: {
        parameters: {
            query?: {
                vendor?: boolean;
                customer?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PartnerResponse"][];
                };
            };
        };
    };
    createPartner: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePartnerRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PartnerResponse"];
                };
            };
        };
    };
    getPartner: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PartnerResponse"];
                };
            };
        };
    };
    listWarehouses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WarehouseResponse"][];
                };
            };
        };
    };
    createWarehouse: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWarehouseRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WarehouseResponse"];
                };
            };
        };
    };
    listPayments: {
        parameters: {
            query?: {
                direction?: "IN" | "OUT";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PaymentResponse"][];
                };
            };
        };
    };
    payIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PayInRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PaymentResponse"];
                };
            };
        };
    };
    payOut: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PayOutRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PaymentResponse"];
                };
            };
        };
    };
    getPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PaymentResponse"];
                };
            };
        };
    };
    apAging: {
        parameters: {
            query?: {
                asOf?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApAgingReport"];
                };
            };
        };
    };
    listReceipts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GoodsReceiptResponse"][];
                };
            };
        };
    };
    receive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGrnRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GoodsReceiptResponse"];
                };
            };
        };
    };
    getReceipt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GoodsReceiptResponse"];
                };
            };
        };
    };
    listOrders_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PurchaseOrderResponse"][];
                };
            };
        };
    };
    createOrder_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePoRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PurchaseOrderResponse"];
                };
            };
        };
    };
    getOrder_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PurchaseOrderResponse"];
                };
            };
        };
    };
    confirm_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PurchaseOrderResponse"];
                };
            };
        };
    };
    listBills: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VendorBillResponse"][];
                };
            };
        };
    };
    postBill: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBillRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VendorBillResponse"];
                };
            };
        };
    };
    getBill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VendorBillResponse"];
                };
            };
        };
    };
    balanceSheet: {
        parameters: {
            query?: {
                asOf?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BalanceSheet"];
                };
            };
        };
    };
    generalLedger: {
        parameters: {
            query?: {
                asOf?: string;
            };
            header?: never;
            path: {
                accountCode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LedgerLineView"][];
                };
            };
        };
    };
    incomeStatement: {
        parameters: {
            query?: {
                asOf?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IncomeStatement"];
                };
            };
        };
    };
    reconciliation: {
        parameters: {
            query?: {
                asOf?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReconciliationReport"];
                };
            };
        };
    };
    trialBalance: {
        parameters: {
            query?: {
                asOf?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TrialBalance"];
                };
            };
        };
    };
    arAging: {
        parameters: {
            query?: {
                asOf?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ArAgingReport"];
                };
            };
        };
    };
    listReturns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomerReturnResponse"][];
                };
            };
        };
    };
    postReturn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReturnRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomerReturnResponse"];
                };
            };
        };
    };
    getReturn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomerReturnResponse"];
                };
            };
        };
    };
    listDeliveries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DeliveryResponse"][];
                };
            };
        };
    };
    deliver: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDeliveryRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DeliveryResponse"];
                };
            };
        };
    };
    getDelivery: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DeliveryResponse"];
                };
            };
        };
    };
    listInvoices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SalesInvoiceResponse"][];
                };
            };
        };
    };
    postInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInvoiceRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SalesInvoiceResponse"];
                };
            };
        };
    };
    getInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SalesInvoiceResponse"];
                };
            };
        };
    };
    listOrders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SalesOrderResponse"][];
                };
            };
        };
    };
    createOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSoRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SalesOrderResponse"];
                };
            };
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SalesOrderResponse"];
                };
            };
        };
    };
    confirm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SalesOrderResponse"];
                };
            };
        };
    };
}
