-- =====================================================================================
-- Sales: sales orders and deliveries. A sales order is a commitment (no posting); a delivery
-- posts the inventory issue + Deferred-COGS debit through the inventory module. Quantities are
-- NUMERIC(19,6); money is NUMERIC(19,4) (unit_price/unit_cost are per-unit, scale 6).
-- =====================================================================================

CREATE TABLE sales_order (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    so_number   VARCHAR(255) NOT NULL UNIQUE,
    partner_id  BIGINT NOT NULL REFERENCES partner (id),
    order_date  DATE NOT NULL,
    status      VARCHAR(255) NOT NULL
                  CHECK (status IN ('DRAFT', 'CONFIRMED', 'PARTIALLY_SHIPPED', 'SHIPPED', 'CLOSED'))
);

CREATE TABLE so_line (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_order_id BIGINT NOT NULL REFERENCES sales_order (id) ON DELETE CASCADE,
    line_no        INTEGER NOT NULL,
    item_id        BIGINT NOT NULL REFERENCES item (id),
    qty_ordered    NUMERIC(19, 6) NOT NULL,
    qty_shipped    NUMERIC(19, 6) NOT NULL DEFAULT 0,
    qty_invoiced   NUMERIC(19, 6) NOT NULL DEFAULT 0,
    unit_price     NUMERIC(19, 6) NOT NULL
);

CREATE INDEX idx_so_line_order ON so_line (sales_order_id);

CREATE TABLE delivery (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_number VARCHAR(255) NOT NULL UNIQUE,
    sales_order_id BIGINT NOT NULL REFERENCES sales_order (id),
    posting_date   DATE NOT NULL,
    status         VARCHAR(255) NOT NULL CHECK (status IN ('POSTED')),
    posted_at      TIMESTAMPTZ NOT NULL
);

CREATE TABLE delivery_line (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_id      BIGINT NOT NULL REFERENCES delivery (id) ON DELETE CASCADE,
    so_line_id       BIGINT NOT NULL REFERENCES so_line (id),
    item_id          BIGINT NOT NULL REFERENCES item (id),
    qty_shipped      NUMERIC(19, 6) NOT NULL,
    qty_invoiced     NUMERIC(19, 6) NOT NULL DEFAULT 0,
    unit_cost        NUMERIC(19, 6) NOT NULL,
    movement_group_id UUID,
    journal_entry_id  BIGINT REFERENCES journal_entry (id)
);

CREATE INDEX idx_delivery_line_delivery ON delivery_line (delivery_id);
CREATE INDEX idx_delivery_line_so_line  ON delivery_line (so_line_id);
