-- =====================================================================================
-- Sales invoices. Posting an invoice recognises revenue + Output VAT against AR, and recognises
-- COGS by clearing the Deferred-COGS parked at delivery (FIFO over delivered-but-uninvoiced lines).
-- Money is NUMERIC(19,4); qty/unit_price are NUMERIC(19,6).
-- =====================================================================================

CREATE TABLE sales_invoice (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number  VARCHAR(255) NOT NULL UNIQUE,
    sales_order_id  BIGINT NOT NULL REFERENCES sales_order (id),
    partner_id      BIGINT NOT NULL REFERENCES partner (id),
    posting_date    DATE NOT NULL,
    goods_amount    NUMERIC(19, 4) NOT NULL,
    vat_amount      NUMERIC(19, 4) NOT NULL,
    cogs_amount     NUMERIC(19, 4) NOT NULL,
    gross_amount    NUMERIC(19, 4) NOT NULL,
    amount_received NUMERIC(19, 4) NOT NULL DEFAULT 0,
    status          VARCHAR(255) NOT NULL
                      CHECK (status IN ('DRAFT', 'POSTED', 'PARTIALLY_PAID', 'PAID')),
    journal_entry_id BIGINT REFERENCES journal_entry (id),
    posted_at        TIMESTAMPTZ
);

CREATE TABLE invoice_line (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_invoice_id BIGINT NOT NULL REFERENCES sales_invoice (id) ON DELETE CASCADE,
    so_line_id       BIGINT NOT NULL REFERENCES so_line (id),
    item_id          BIGINT NOT NULL REFERENCES item (id),
    qty              NUMERIC(19, 6) NOT NULL,
    unit_price       NUMERIC(19, 6) NOT NULL,
    line_net         NUMERIC(19, 4) NOT NULL,
    line_vat         NUMERIC(19, 4) NOT NULL,
    line_cogs        NUMERIC(19, 4) NOT NULL
);

CREATE INDEX idx_invoice_line_invoice ON invoice_line (sales_invoice_id);
CREATE INDEX idx_invoice_line_so_line ON invoice_line (so_line_id);
