-- =====================================================================================
-- Customer returns (credit notes). A return reverses a posted, unpaid invoice: goods come back
-- (SALES_RETURN: Dr Finished Goods / Cr Deferred-COGS) and a credit note reverses revenue + Output
-- VAT + AR and un-recognises COGS (Dr Deferred-COGS / Cr COGS), netting every account to zero.
-- =====================================================================================

-- A fully-returned invoice leaves the receivable cycle.
ALTER TABLE sales_invoice DROP CONSTRAINT sales_invoice_status_check;
ALTER TABLE sales_invoice ADD CONSTRAINT sales_invoice_status_check
    CHECK (status IN ('DRAFT', 'POSTED', 'PARTIALLY_PAID', 'PAID', 'RETURNED'));

CREATE TABLE customer_return (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_number    VARCHAR(255) NOT NULL UNIQUE,
    sales_invoice_id BIGINT NOT NULL REFERENCES sales_invoice (id),
    sales_order_id   BIGINT NOT NULL REFERENCES sales_order (id),
    partner_id       BIGINT NOT NULL REFERENCES partner (id),
    posting_date     DATE NOT NULL,
    goods_amount     NUMERIC(19, 4) NOT NULL,
    vat_amount       NUMERIC(19, 4) NOT NULL,
    cogs_amount      NUMERIC(19, 4) NOT NULL,
    gross_amount     NUMERIC(19, 4) NOT NULL,
    status           VARCHAR(255) NOT NULL CHECK (status IN ('POSTED')),
    credit_note_journal_entry_id BIGINT REFERENCES journal_entry (id),
    posted_at        TIMESTAMPTZ NOT NULL
);

CREATE TABLE customer_return_line (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_return_id BIGINT NOT NULL REFERENCES customer_return (id) ON DELETE CASCADE,
    so_line_id         BIGINT NOT NULL REFERENCES so_line (id),
    item_id            BIGINT NOT NULL REFERENCES item (id),
    qty                NUMERIC(19, 6) NOT NULL,
    line_net           NUMERIC(19, 4) NOT NULL,
    line_vat           NUMERIC(19, 4) NOT NULL,
    line_cogs          NUMERIC(19, 4) NOT NULL,
    movement_group_id  UUID,
    stock_journal_entry_id BIGINT REFERENCES journal_entry (id)
);

CREATE INDEX idx_customer_return_line_return ON customer_return_line (customer_return_id);
