-- =====================================================================================
-- Manufacturing: bills of material and work orders. A BOM is master data (no posting). A work order
-- snapshots its BOM at release (frozen), consumes components into WIP at issue, and produces finished
-- goods at completion. Quantities/costs are NUMERIC(19,6); money is NUMERIC(19,4).
-- =====================================================================================

CREATE TABLE bill_of_materials (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_item_id BIGINT NOT NULL REFERENCES item (id),
    version        INTEGER NOT NULL DEFAULT 1,
    output_qty     NUMERIC(19, 6) NOT NULL,
    status         VARCHAR(255) NOT NULL CHECK (status IN ('ACTIVE', 'ARCHIVED')),
    UNIQUE (parent_item_id, version)
);

CREATE TABLE bom_component (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bom_id       BIGINT NOT NULL REFERENCES bill_of_materials (id) ON DELETE CASCADE,
    line_no      INTEGER NOT NULL,
    component_item_id BIGINT NOT NULL REFERENCES item (id),
    qty_per      NUMERIC(19, 6) NOT NULL,
    scrap_pct    NUMERIC(9, 6) NOT NULL DEFAULT 0
);

CREATE INDEX idx_bom_component_bom ON bom_component (bom_id);

CREATE TABLE work_order (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wo_number       VARCHAR(255) NOT NULL UNIQUE,
    item_id         BIGINT NOT NULL REFERENCES item (id),
    bom_id          BIGINT NOT NULL REFERENCES bill_of_materials (id),
    qty_to_produce  NUMERIC(19, 6) NOT NULL,
    qty_produced    NUMERIC(19, 6) NOT NULL DEFAULT 0,
    wip_location_id BIGINT REFERENCES location (id),
    total_component_cost NUMERIC(19, 4) NOT NULL DEFAULT 0,
    status          VARCHAR(255) NOT NULL
                      CHECK (status IN ('DRAFT', 'RELEASED', 'IN_PROGRESS', 'DONE', 'CANCELLED'))
);

CREATE TABLE work_order_component (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id BIGINT NOT NULL REFERENCES work_order (id) ON DELETE CASCADE,
    line_no       INTEGER NOT NULL,
    component_item_id BIGINT NOT NULL REFERENCES item (id),
    planned_qty   NUMERIC(19, 6) NOT NULL,
    consumed_qty  NUMERIC(19, 6) NOT NULL DEFAULT 0,
    consumed_value NUMERIC(19, 4) NOT NULL DEFAULT 0,
    movement_group_id UUID,
    journal_entry_id  BIGINT REFERENCES journal_entry (id)
);

CREATE INDEX idx_wo_component_wo ON work_order_component (work_order_id);
