-- =====================================================================================
-- IAM: persisted application users, replacing the in-memory {noop} store in SecurityConfig.
-- Five fixed accounts (no registration, no user CRUD). Roles are held as a CSV of role codes
-- (a closed set, never queried by role — so a plain VARCHAR keeps Hibernate ddl-auto=validate
-- frictionless). The guest account has an empty roles string: it authenticates (can read) but
-- holds no write role, so every POST authorization (hasRole(...)) returns 403 naturally.
--
-- The rows are inserted at startup by UserSeeder (idempotent, profile-independent) using the
-- BCryptPasswordEncoder, so password hashes are not baked into this migration.
-- =====================================================================================
CREATE TABLE app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    roles         VARCHAR(255) NOT NULL DEFAULT '',
    enabled       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
