-- =====================================================================================
-- Append-only audit trail of sensitive actions: every posted journal entry (covers all financial
-- activity, since LedgerPostingService is the one posting entry point), fiscal-period close/reopen,
-- and login success/failure. Written by an AFTER_COMMIT event listener, so a row exists only for an
-- action that actually committed. Append-only (no UPDATE/DELETE), mirroring stock_ledger_entry (V4).
-- =====================================================================================
CREATE TABLE audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type  VARCHAR(64)  NOT NULL,   -- JOURNAL_POSTED / PERIOD_CLOSED / PERIOD_REOPENED / LOGIN_SUCCESS / LOGIN_FAILURE
    actor       VARCHAR(255) NOT NULL,
    occurred_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    ref_type    VARCHAR(64),             -- JOURNAL_ENTRY / FISCAL_PERIOD (null for login)
    ref_id      VARCHAR(255),            -- entry no / period code
    summary     VARCHAR(500) NOT NULL,   -- human-readable line
    detail      VARCHAR(2000)            -- optional extra (e.g. source document)
);

CREATE INDEX idx_audit_log_occurred ON audit_log (occurred_at DESC);
CREATE INDEX idx_audit_log_event ON audit_log (event_type);
CREATE INDEX idx_audit_log_actor ON audit_log (actor);

CREATE OR REPLACE FUNCTION protect_audit_log() RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'audit_log is append-only (op=%, id=%)', TG_OP, COALESCE(OLD.id, NEW.id);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER audit_log_append_only
    BEFORE UPDATE OR DELETE ON audit_log
    FOR EACH ROW
    EXECUTE FUNCTION protect_audit_log();
