-- =====================================================================================
-- Human Resources master data: departments, positions and employees. Departments carry a
-- GL budget account (payroll expense) used by the later payroll → ledger posting slice.
-- =====================================================================================

CREATE TABLE department (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                VARCHAR(255) NOT NULL UNIQUE,
    name                VARCHAR(255) NOT NULL,
    budget_account_code VARCHAR(255),
    active              BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE position (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(255) NOT NULL UNIQUE,
    title           VARCHAR(255) NOT NULL,
    standard_salary NUMERIC(19, 4),
    active          BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE employee (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code             VARCHAR(255) NOT NULL UNIQUE,
    first_name       VARCHAR(255) NOT NULL,
    last_name        VARCHAR(255) NOT NULL,
    department_id    BIGINT NOT NULL REFERENCES department (id),
    position_id      BIGINT NOT NULL REFERENCES position (id),
    monthly_salary   NUMERIC(19, 4),
    status           VARCHAR(255) NOT NULL
                        CHECK (status IN ('ACTIVE', 'ON_LEAVE', 'TERMINATED')),
    hire_date        DATE NOT NULL,
    termination_date DATE
);
