-- =====================================================================================
-- HR time management (B2): daily attendance, leave requests (with an approval lifecycle) and
-- weekly timesheets (regular + overtime hours). Pure HR data — none of it posts to the ledger;
-- payroll (B3) later reads it to compute pay.
-- =====================================================================================

CREATE TABLE attendance (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id  BIGINT NOT NULL REFERENCES employee (id),
    work_date    DATE NOT NULL,
    status       VARCHAR(255) NOT NULL
                    CHECK (status IN ('PRESENT', 'ABSENT', 'LATE', 'LEAVE', 'REMOTE')),
    worked_hours NUMERIC(6, 2),
    note         VARCHAR(500),
    CONSTRAINT uq_attendance_employee_day UNIQUE (employee_id, work_date)
);

CREATE TABLE leave_request (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employee (id),
    leave_type  VARCHAR(255) NOT NULL
                    CHECK (leave_type IN ('ANNUAL', 'SICK', 'PERSONAL', 'UNPAID')),
    start_date  DATE NOT NULL,
    end_date    DATE NOT NULL,
    days        NUMERIC(6, 2) NOT NULL,
    reason      VARCHAR(500),
    status      VARCHAR(255) NOT NULL
                    CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    decided_by  VARCHAR(255),
    decided_on  DATE
);

CREATE TABLE timesheet (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id    BIGINT NOT NULL REFERENCES employee (id),
    week_ending    DATE NOT NULL,
    regular_hours  NUMERIC(6, 2) NOT NULL,
    overtime_hours NUMERIC(6, 2) NOT NULL,
    status         VARCHAR(255) NOT NULL
                    CHECK (status IN ('DRAFT', 'SUBMITTED', 'APPROVED')),
    note           VARCHAR(500),
    CONSTRAINT uq_timesheet_employee_week UNIQUE (employee_id, week_ending)
);

CREATE INDEX idx_attendance_employee ON attendance (employee_id);
CREATE INDEX idx_leave_request_employee ON leave_request (employee_id);
CREATE INDEX idx_timesheet_employee ON timesheet (employee_id);
