-- =====================================================================================
-- HR payroll (B3): the salary GL accounts plus the payroll run and its per-employee lines.
-- Posting a run hands the ledger one balanced entry: Dr 6100 salaries expense / Cr 2200 net pay
-- payable + Cr 2210 tax withheld + Cr 2220 insurance payable. Only GL accounts are touched (no
-- AP/AR/inventory subledger), so the reconciliation health-check stays green.
-- =====================================================================================

INSERT INTO account (code, name, account_class, normal_balance, postable, currency_code, active) VALUES
    ('6100', 'Salaries Expense',            'EXPENSE',   'DEBIT',  TRUE, 'TWD', TRUE),
    ('2200', 'Net Pay Payable',             'LIABILITY', 'CREDIT', TRUE, 'TWD', TRUE),
    ('2210', 'Employee Tax Withheld',       'LIABILITY', 'CREDIT', TRUE, 'TWD', TRUE),
    ('2220', 'Insurance Payable',           'LIABILITY', 'CREDIT', TRUE, 'TWD', TRUE);

CREATE TABLE payroll (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_year     INTEGER NOT NULL,
    period_month    INTEGER NOT NULL CHECK (period_month BETWEEN 1 AND 12),
    status          VARCHAR(255) NOT NULL CHECK (status IN ('DRAFT', 'POSTED')),
    gross_total     NUMERIC(19, 2) NOT NULL,
    tax_total       NUMERIC(19, 2) NOT NULL,
    insurance_total NUMERIC(19, 2) NOT NULL,
    net_total       NUMERIC(19, 2) NOT NULL,
    posting_date    DATE,
    journal_entry_id BIGINT,
    CONSTRAINT uq_payroll_period UNIQUE (period_year, period_month)
);

CREATE TABLE payroll_line (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payroll_id  BIGINT NOT NULL REFERENCES payroll (id),
    employee_id BIGINT NOT NULL REFERENCES employee (id),
    gross       NUMERIC(19, 2) NOT NULL,
    tax         NUMERIC(19, 2) NOT NULL,
    insurance   NUMERIC(19, 2) NOT NULL,
    net         NUMERIC(19, 2) NOT NULL
);

CREATE INDEX idx_payroll_line_payroll ON payroll_line (payroll_id);
