-- =====================================================================================
-- Ledger core schema. The double-entry General Ledger is module zero: every other module
-- posts into journal_entry/journal_line through the application's LedgerPostingService.
-- Correctness invariants are enforced in depth here at the database level.
-- =====================================================================================

-- ---- Chart of accounts -------------------------------------------------------------
CREATE TABLE account (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR(255) NOT NULL UNIQUE,
    name          VARCHAR(255) NOT NULL,
    account_class VARCHAR(255) NOT NULL
                    CHECK (account_class IN ('ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE')),
    normal_balance VARCHAR(255) NOT NULL CHECK (normal_balance IN ('DEBIT', 'CREDIT')),
    parent_id     BIGINT REFERENCES account (id),
    postable      BOOLEAN NOT NULL DEFAULT TRUE,
    currency_code VARCHAR(255) NOT NULL,
    active        BOOLEAN NOT NULL DEFAULT TRUE
);

-- ---- Journals (books of entry) -----------------------------------------------------
CREATE TABLE journal (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL
);

-- ---- Fiscal calendar ---------------------------------------------------------------
CREATE TABLE fiscal_year (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(255) NOT NULL UNIQUE,
    start_date DATE NOT NULL,
    end_date   DATE NOT NULL,
    status     VARCHAR(255) NOT NULL CHECK (status IN ('OPEN', 'CLOSED'))
);

CREATE TABLE fiscal_period (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fiscal_year_id BIGINT NOT NULL REFERENCES fiscal_year (id),
    period_no      INTEGER NOT NULL CHECK (period_no BETWEEN 1 AND 12),
    start_date     DATE NOT NULL,
    end_date       DATE NOT NULL,
    status         VARCHAR(255) NOT NULL CHECK (status IN ('OPEN', 'CLOSED', 'LOCKED')),
    UNIQUE (fiscal_year_id, period_no)
);

-- ---- Gapless numbering counter -----------------------------------------------------
CREATE TABLE number_sequence (
    scope      VARCHAR(255) PRIMARY KEY,
    prefix     VARCHAR(255) NOT NULL,
    next_value BIGINT NOT NULL,
    padding    INTEGER NOT NULL
);

-- ---- Journal entries (immutable accounting facts) ----------------------------------
CREATE TABLE journal_entry (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_no             BIGINT,
    journal_id           BIGINT NOT NULL REFERENCES journal (id),
    fiscal_period_id     BIGINT NOT NULL REFERENCES fiscal_period (id),
    posting_date         DATE NOT NULL,
    memo                 VARCHAR(500),
    status               VARCHAR(255) NOT NULL
                            CHECK (status IN ('DRAFT', 'POSTED', 'REVERSED', 'VOID')),
    source_doc_type      VARCHAR(255),
    source_doc_id        VARCHAR(255),
    source_event         VARCHAR(255),
    reverses_entry_id    BIGINT REFERENCES journal_entry (id),
    reversed_by_entry_id BIGINT REFERENCES journal_entry (id),
    currency_code        VARCHAR(255) NOT NULL,
    posted_at            TIMESTAMPTZ,
    posted_by            VARCHAR(255),
    created_at           TIMESTAMPTZ NOT NULL,
    created_by           VARCHAR(255)
);

-- entry_no is gapless and assigned only at POST time; unique when present.
CREATE UNIQUE INDEX uq_journal_entry_no ON journal_entry (entry_no) WHERE entry_no IS NOT NULL;

-- Idempotency: a (source document, event) triple posts at most one live entry. Keyed on
-- source_event as well so one document can legitimately post several legs (receipt, consume,
-- produce, ...) while a retry of the SAME leg is rejected.
CREATE UNIQUE INDEX uq_journal_entry_source
    ON journal_entry (source_doc_type, source_doc_id, source_event)
    WHERE source_doc_type IS NOT NULL AND status IN ('DRAFT', 'POSTED');

-- ---- Journal lines -----------------------------------------------------------------
CREATE TABLE journal_line (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_entry_id BIGINT NOT NULL REFERENCES journal_entry (id) ON DELETE CASCADE,
    line_no          INTEGER NOT NULL,
    account_id       BIGINT NOT NULL REFERENCES account (id),
    debit            NUMERIC(19, 4) NOT NULL DEFAULT 0 CHECK (debit >= 0),
    credit           NUMERIC(19, 4) NOT NULL DEFAULT 0 CHECK (credit >= 0),
    memo             VARCHAR(500),
    partner_id       BIGINT,
    product_id       BIGINT,
    mo_id            BIGINT,
    -- exactly one side of every line is non-zero
    CONSTRAINT chk_journal_line_one_side CHECK ((debit = 0) <> (credit = 0))
);

CREATE INDEX idx_journal_line_entry   ON journal_line (journal_entry_id);
CREATE INDEX idx_journal_line_account ON journal_line (account_id);

-- =====================================================================================
-- Invariant 1 (defense in depth): a POSTED entry's debits must equal its credits and be
-- non-zero. Checked at COMMIT via a deferred constraint trigger, so the application can
-- insert the header and its lines in any order within one transaction.
-- =====================================================================================
CREATE OR REPLACE FUNCTION assert_journal_entry_balanced() RETURNS TRIGGER AS $$
DECLARE
    total_debit  NUMERIC(19, 4);
    total_credit NUMERIC(19, 4);
BEGIN
    IF NEW.status = 'POSTED' THEN
        SELECT COALESCE(SUM(debit), 0), COALESCE(SUM(credit), 0)
          INTO total_debit, total_credit
          FROM journal_line
         WHERE journal_entry_id = NEW.id;

        IF total_debit <> total_credit THEN
            RAISE EXCEPTION 'journal entry % is unbalanced: debit=% credit=%',
                NEW.id, total_debit, total_credit;
        END IF;
        IF total_debit = 0 THEN
            RAISE EXCEPTION 'journal entry % has zero total', NEW.id;
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE CONSTRAINT TRIGGER journal_entry_balanced
    AFTER INSERT OR UPDATE ON journal_entry
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW
    EXECUTE FUNCTION assert_journal_entry_balanced();

-- =====================================================================================
-- Invariant 2: a POSTED entry is immutable. Its financial fields cannot be edited and it
-- cannot be deleted; only a transition to REVERSED/VOID (with the reversed_by link) is allowed.
-- =====================================================================================
CREATE OR REPLACE FUNCTION protect_posted_entry() RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF OLD.status IN ('POSTED', 'REVERSED') THEN
            RAISE EXCEPTION 'cannot delete posted journal entry %', OLD.id;
        END IF;
        RETURN OLD;
    END IF;

    -- UPDATE
    IF OLD.status = 'POSTED' THEN
        IF NEW.status NOT IN ('POSTED', 'REVERSED', 'VOID') THEN
            RAISE EXCEPTION 'invalid status change from POSTED on entry %', OLD.id;
        END IF;
        IF NEW.entry_no         IS DISTINCT FROM OLD.entry_no
            OR NEW.journal_id       IS DISTINCT FROM OLD.journal_id
            OR NEW.fiscal_period_id IS DISTINCT FROM OLD.fiscal_period_id
            OR NEW.posting_date     IS DISTINCT FROM OLD.posting_date
            OR NEW.currency_code    IS DISTINCT FROM OLD.currency_code
            OR NEW.source_doc_type  IS DISTINCT FROM OLD.source_doc_type
            OR NEW.source_doc_id    IS DISTINCT FROM OLD.source_doc_id
            OR NEW.source_event     IS DISTINCT FROM OLD.source_event
            OR NEW.memo             IS DISTINCT FROM OLD.memo THEN
            RAISE EXCEPTION 'cannot modify financial fields of posted journal entry %', OLD.id;
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER journal_entry_protect
    BEFORE UPDATE OR DELETE ON journal_entry
    FOR EACH ROW
    EXECUTE FUNCTION protect_posted_entry();

-- Lines belonging to a POSTED entry cannot be modified or deleted (they are inserted while the
-- entry is being posted, so INSERT is allowed even once the parent is POSTED).
CREATE OR REPLACE FUNCTION protect_posted_line() RETURNS TRIGGER AS $$
DECLARE
    parent_status VARCHAR(255);
BEGIN
    IF TG_OP = 'DELETE' THEN
        SELECT status INTO parent_status FROM journal_entry WHERE id = OLD.journal_entry_id;
        IF parent_status IN ('POSTED', 'REVERSED') THEN
            RAISE EXCEPTION 'cannot delete line of posted journal entry %', OLD.journal_entry_id;
        END IF;
        RETURN OLD;
    END IF;

    IF TG_OP = 'UPDATE' THEN
        SELECT status INTO parent_status FROM journal_entry WHERE id = NEW.journal_entry_id;
        IF parent_status IN ('POSTED', 'REVERSED') THEN
            RAISE EXCEPTION 'cannot modify line of posted journal entry %', NEW.journal_entry_id;
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER journal_line_protect
    BEFORE INSERT OR UPDATE OR DELETE ON journal_line
    FOR EACH ROW
    EXECUTE FUNCTION protect_posted_line();
