-- =====================================================================================
-- Budgeting (C1 finance analytics): a monthly budget per GL account per fiscal year. The
-- budget-variance report compares these planned figures against actual posted GL movement.
-- =====================================================================================

CREATE TABLE budget (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_year    INTEGER NOT NULL,
    account_code   VARCHAR(255) NOT NULL,
    monthly_budget NUMERIC(19, 2) NOT NULL,
    CONSTRAINT uq_budget_year_account UNIQUE (period_year, account_code)
);
