-- =====================================================================================
-- Equipment / OEE (C5): production machines and their daily production logs (scheduled time,
-- downtime with a reason, produced vs. good units). Feeds the OEE dashboard — Availability ×
-- Performance × Quality — and the downtime-by-reason breakdown. Pure operational data, no posting.
-- =====================================================================================

CREATE TABLE equipment (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                 VARCHAR(255) NOT NULL UNIQUE,
    name                 VARCHAR(255) NOT NULL,
    ideal_units_per_hour NUMERIC(19, 2) NOT NULL,
    active               BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE production_log (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_id     BIGINT NOT NULL REFERENCES equipment (id),
    log_date         DATE NOT NULL,
    planned_minutes  INTEGER NOT NULL,
    downtime_minutes INTEGER NOT NULL,
    downtime_reason  VARCHAR(255),
    produced_units   INTEGER NOT NULL,
    good_units       INTEGER NOT NULL,
    CONSTRAINT uq_production_log_equipment_day UNIQUE (equipment_id, log_date)
);

CREATE INDEX idx_production_log_equipment ON production_log (equipment_id);
