-- =====================================================================================
-- Master data: items, warehouses, typed locations and the inventory→ledger posting rules.
-- Quantity/cost columns are NUMERIC(19,6) (finer than the ledger's money NUMERIC(19,4)).
-- =====================================================================================

-- ---- Items -------------------------------------------------------------------------
CREATE TABLE item (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku              VARCHAR(255) NOT NULL UNIQUE,
    name             VARCHAR(255) NOT NULL,
    item_type        VARCHAR(255) NOT NULL
                        CHECK (item_type IN ('RAW', 'WIP', 'FINISHED', 'SERVICE')),
    uom              VARCHAR(255) NOT NULL,
    stocked          BOOLEAN NOT NULL DEFAULT TRUE,
    standard_cost    NUMERIC(19, 6) NOT NULL DEFAULT 0 CHECK (standard_cost >= 0),
    valuation_method VARCHAR(255) NOT NULL
                        CHECK (valuation_method IN ('MOVING_AVERAGE', 'STANDARD')),
    reorder_point    NUMERIC(19, 6),
    reorder_qty      NUMERIC(19, 6)
);

-- ---- Warehouses --------------------------------------------------------------------
CREATE TABLE warehouse (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code   VARCHAR(255) NOT NULL UNIQUE,
    name   VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

-- ---- Locations (typed bins) --------------------------------------------------------
CREATE TABLE location (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id  BIGINT NOT NULL REFERENCES warehouse (id),
    code          VARCHAR(255) NOT NULL,
    location_type VARCHAR(255) NOT NULL
                    CHECK (location_type IN ('STOCK', 'RECEIVING', 'SHIPPING', 'PRODUCTION_WIP',
                                             'SCRAP', 'VENDOR', 'CUSTOMER', 'INVENTORY_LOSS')),
    active        BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE (warehouse_id, code)
);

-- ---- Inventory → ledger posting rules ----------------------------------------------
-- An INVENTORY-role rule is keyed by item_type (the control account); a COUNTER-role rule by
-- movement_type (the offset account). The unused key column is null for that role; two partial
-- unique indexes keep each role's key unique.
CREATE TABLE inventory_posting_rule (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role          VARCHAR(255) NOT NULL CHECK (role IN ('INVENTORY', 'COUNTER')),
    item_type     VARCHAR(255)
                    CHECK (item_type IN ('RAW', 'WIP', 'FINISHED', 'SERVICE')),
    movement_type VARCHAR(255)
                    CHECK (movement_type IN ('RECEIPT', 'ISSUE', 'ADJUSTMENT_IN',
                                             'ADJUSTMENT_OUT', 'TRANSFER')),
    account_code  VARCHAR(255) NOT NULL
);

CREATE UNIQUE INDEX uq_posting_rule_inventory ON inventory_posting_rule (item_type)
    WHERE role = 'INVENTORY';
CREATE UNIQUE INDEX uq_posting_rule_counter ON inventory_posting_rule (movement_type)
    WHERE role = 'COUNTER';

-- ---- Number sequence for stock-adjustment documents (unique-monotonic, non-gapless) ----
INSERT INTO number_sequence (scope, prefix, next_value, padding)
VALUES ('STOCK_ADJUSTMENT', 'ADJ', 1, 6);

-- ---- Seed: one warehouse with the full set of typed locations ----------------------
INSERT INTO warehouse (code, name) VALUES ('WH1', 'Main Warehouse');

INSERT INTO location (warehouse_id, code, location_type)
SELECT w.id, v.code, v.ltype
FROM warehouse w
CROSS JOIN (VALUES
    ('STOCK',     'STOCK'),
    ('RECEIVING', 'RECEIVING'),
    ('SHIPPING',  'SHIPPING'),
    ('WIP',       'PRODUCTION_WIP'),
    ('SCRAP',     'SCRAP'),
    ('LOSS',      'INVENTORY_LOSS')
) AS v(code, ltype)
WHERE w.code = 'WH1';

-- ---- Seed: posting rules -----------------------------------------------------------
-- Inventory control accounts by item type.
INSERT INTO inventory_posting_rule (role, item_type, account_code) VALUES
    ('INVENTORY', 'RAW',      '1310'),
    ('INVENTORY', 'WIP',      '1320'),
    ('INVENTORY', 'FINISHED', '1330');

-- Counter (offset) accounts by movement type. Phase 1 only adjusts; receipts/issues come later.
INSERT INTO inventory_posting_rule (role, movement_type, account_code) VALUES
    ('COUNTER', 'ADJUSTMENT_IN',  '6000'),
    ('COUNTER', 'ADJUSTMENT_OUT', '6000');
