-- =====================================================================================
-- Inventory subledger. stock_ledger_entry is the immutable, append-only source of truth;
-- item_cost_state is the moving-average cache. Quantities/costs are NUMERIC(19,6); value is
-- money NUMERIC(19,4) so the subledger reconciles exactly to the GL inventory control accounts.
-- =====================================================================================

-- ---- Stock ledger (append-only subledger) ------------------------------------------
CREATE TABLE stock_ledger_entry (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movement_group_id UUID NOT NULL,
    item_id           BIGINT NOT NULL REFERENCES item (id),
    location_id       BIGINT NOT NULL REFERENCES location (id),
    qty_delta         NUMERIC(19, 6) NOT NULL,
    unit_cost         NUMERIC(19, 6) NOT NULL,
    value_delta       NUMERIC(19, 4) NOT NULL,
    movement_type     VARCHAR(255) NOT NULL
                        CHECK (movement_type IN ('RECEIPT', 'ISSUE', 'ADJUSTMENT_IN',
                                                 'ADJUSTMENT_OUT', 'TRANSFER')),
    source_doc_type   VARCHAR(255) NOT NULL,
    source_doc_id     VARCHAR(255) NOT NULL,
    journal_entry_id  BIGINT REFERENCES journal_entry (id),
    posted_at         TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_stock_ledger_item     ON stock_ledger_entry (item_id);
CREATE INDEX idx_stock_ledger_location ON stock_ledger_entry (location_id);
CREATE INDEX idx_stock_ledger_group    ON stock_ledger_entry (movement_group_id);

-- The subledger is append-only: once written, a leg can never be updated or deleted.
CREATE OR REPLACE FUNCTION protect_stock_ledger_entry() RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'stock_ledger_entry is append-only (op=%, id=%)',
        TG_OP, COALESCE(OLD.id, NEW.id);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER stock_ledger_entry_append_only
    BEFORE UPDATE OR DELETE ON stock_ledger_entry
    FOR EACH ROW
    EXECUTE FUNCTION protect_stock_ledger_entry();

-- ---- Moving-average cost cache (one row per stocked item) ---------------------------
CREATE TABLE item_cost_state (
    item_id       BIGINT PRIMARY KEY REFERENCES item (id),
    on_hand_qty   NUMERIC(19, 6) NOT NULL,
    avg_unit_cost NUMERIC(19, 6) NOT NULL,
    total_value   NUMERIC(19, 4) NOT NULL,
    version       BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT chk_item_cost_state_non_negative CHECK (on_hand_qty >= 0 AND total_value >= 0)
);

-- ---- Stock-adjustment documents ----------------------------------------------------
CREATE TABLE stock_adjustment (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adjustment_number VARCHAR(255) NOT NULL UNIQUE,
    item_id           BIGINT NOT NULL REFERENCES item (id),
    location_id       BIGINT NOT NULL REFERENCES location (id),
    qty_delta         NUMERIC(19, 6) NOT NULL,
    unit_cost         NUMERIC(19, 6),
    reason            VARCHAR(255) NOT NULL,
    status            VARCHAR(255) NOT NULL CHECK (status IN ('DRAFT', 'POSTED')),
    movement_group_id UUID,
    journal_entry_id  BIGINT REFERENCES journal_entry (id),
    posted_at         TIMESTAMPTZ
);
