-- =====================================================================================
-- Phase 2 foundation: business partners, a VAT rate, and the reference data the
-- procure-to-pay flow needs (VENDOR/CUSTOMER locations, the receipt posting rule, and the
-- purchasing/payment document number sequences).
-- =====================================================================================

-- ---- Business partners (vendor and/or customer) ------------------------------------
CREATE TABLE partner (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code               VARCHAR(255) NOT NULL UNIQUE,
    name               VARCHAR(255) NOT NULL,
    is_vendor          BOOLEAN NOT NULL DEFAULT FALSE,
    is_customer        BOOLEAN NOT NULL DEFAULT FALSE,
    tax_id             VARCHAR(255),
    payment_terms_days INTEGER NOT NULL DEFAULT 30,
    ap_account_code    VARCHAR(255),
    ar_account_code    VARCHAR(255),
    active             BOOLEAN NOT NULL DEFAULT TRUE
);

-- ---- VAT rates (single rate in the MVP, but data not a constant) -------------------
CREATE TABLE tax_rate (
    code   VARCHAR(255) PRIMARY KEY,
    rate   NUMERIC(9, 6) NOT NULL CHECK (rate >= 0),
    active BOOLEAN NOT NULL DEFAULT TRUE
);

INSERT INTO tax_rate (code, rate) VALUES ('STANDARD', 0.050000);

-- ---- VENDOR / CUSTOMER typed locations on the existing warehouse --------------------
-- Receipts move VENDOR → STOCK; deliveries (Phase 3) move STOCK → CUSTOMER.
INSERT INTO location (warehouse_id, code, location_type)
SELECT w.id, v.code, v.ltype
FROM warehouse w
CROSS JOIN (VALUES ('VENDOR', 'VENDOR'), ('CUSTOMER', 'CUSTOMER')) AS v(code, ltype)
WHERE w.code = 'WH1';

-- ---- Receipt posting rule: a goods receipt's counter account is GR-IR clearing ------
INSERT INTO inventory_posting_rule (role, movement_type, account_code)
VALUES ('COUNTER', 'RECEIPT', '2150');

-- ---- Document number sequences (unique-monotonic + prefix) --------------------------
INSERT INTO number_sequence (scope, prefix, next_value, padding) VALUES
    ('PURCHASE_ORDER', 'PO',   1, 6),
    ('GOODS_RECEIPT',  'GRN',  1, 6),
    ('VENDOR_BILL',    'BILL', 1, 6),
    ('PAYMENT',        'PAY',  1, 6);
