-- =====================================================================================
-- Purchasing: purchase orders and goods receipts. A PO is a commitment (no posting); a goods
-- receipt posts the inventory receipt + GR-IR credit through the inventory module. Quantities
-- are NUMERIC(19,6); money is NUMERIC(19,4) (unit_price is a price, scale 6).
-- =====================================================================================

CREATE TABLE purchase_order (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_number    VARCHAR(255) NOT NULL UNIQUE,
    partner_id   BIGINT NOT NULL REFERENCES partner (id),
    order_date   DATE NOT NULL,
    status       VARCHAR(255) NOT NULL
                   CHECK (status IN ('DRAFT', 'CONFIRMED', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CLOSED'))
);

CREATE TABLE po_line (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id BIGINT NOT NULL REFERENCES purchase_order (id) ON DELETE CASCADE,
    line_no           INTEGER NOT NULL,
    item_id           BIGINT NOT NULL REFERENCES item (id),
    qty_ordered       NUMERIC(19, 6) NOT NULL,
    qty_received      NUMERIC(19, 6) NOT NULL DEFAULT 0,
    qty_billed        NUMERIC(19, 6) NOT NULL DEFAULT 0,
    unit_price        NUMERIC(19, 6) NOT NULL
);

CREATE INDEX idx_po_line_order ON po_line (purchase_order_id);

CREATE TABLE goods_receipt (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grn_number        VARCHAR(255) NOT NULL UNIQUE,
    purchase_order_id BIGINT NOT NULL REFERENCES purchase_order (id),
    posting_date      DATE NOT NULL,
    status            VARCHAR(255) NOT NULL CHECK (status IN ('POSTED')),
    posted_at         TIMESTAMPTZ NOT NULL
);

CREATE TABLE grn_line (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goods_receipt_id BIGINT NOT NULL REFERENCES goods_receipt (id) ON DELETE CASCADE,
    po_line_id       BIGINT NOT NULL REFERENCES po_line (id),
    item_id          BIGINT NOT NULL REFERENCES item (id),
    qty_received     NUMERIC(19, 6) NOT NULL,
    qty_billed       NUMERIC(19, 6) NOT NULL DEFAULT 0,
    unit_cost        NUMERIC(19, 6) NOT NULL,
    movement_group_id UUID,
    journal_entry_id  BIGINT REFERENCES journal_entry (id)
);

CREATE INDEX idx_grn_line_receipt ON grn_line (goods_receipt_id);
CREATE INDEX idx_grn_line_po_line ON grn_line (po_line_id);
