-- =====================================================================================
-- Vendor bills (supplier invoices). A posted bill clears GR-IR for its matched receipts,
-- records Input VAT and the AP credit, and (on a price variance) revalues inventory. Money
-- amounts are NUMERIC(19,4); quantity/price are NUMERIC(19,6).
-- =====================================================================================

CREATE TABLE vendor_bill (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_number       VARCHAR(255) NOT NULL UNIQUE,
    purchase_order_id BIGINT NOT NULL REFERENCES purchase_order (id),
    partner_id        BIGINT NOT NULL REFERENCES partner (id),
    posting_date      DATE NOT NULL,
    goods_amount      NUMERIC(19, 4) NOT NULL,
    vat_amount        NUMERIC(19, 4) NOT NULL,
    gross_amount      NUMERIC(19, 4) NOT NULL,
    amount_paid       NUMERIC(19, 4) NOT NULL DEFAULT 0,
    status            VARCHAR(255) NOT NULL
                        CHECK (status IN ('DRAFT', 'POSTED', 'PARTIALLY_PAID', 'PAID')),
    journal_entry_id  BIGINT REFERENCES journal_entry (id),
    posted_at         TIMESTAMPTZ
);

CREATE TABLE bill_line (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_bill_id BIGINT NOT NULL REFERENCES vendor_bill (id) ON DELETE CASCADE,
    po_line_id     BIGINT NOT NULL REFERENCES po_line (id),
    item_id        BIGINT NOT NULL REFERENCES item (id),
    qty            NUMERIC(19, 6) NOT NULL,
    unit_price     NUMERIC(19, 6) NOT NULL,
    line_net       NUMERIC(19, 4) NOT NULL,
    line_vat       NUMERIC(19, 4) NOT NULL,
    match_status   VARCHAR(255) NOT NULL CHECK (match_status IN ('MATCHED', 'PRICE_VARIANCE'))
);

CREATE INDEX idx_bill_line_bill ON bill_line (vendor_bill_id);
