-- =====================================================================================
-- Payments and their allocations. An outgoing payment posts Dr AP / Cr Cash and allocates the
-- amount across the vendor's open bills. The direction (IN|OUT) lets the same machinery serve
-- customer receipts in Phase 3. Amounts are money NUMERIC(19,4).
-- =====================================================================================

CREATE TABLE payment (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pay_number       VARCHAR(255) NOT NULL UNIQUE,
    direction        VARCHAR(255) NOT NULL CHECK (direction IN ('IN', 'OUT')),
    partner_id       BIGINT NOT NULL REFERENCES partner (id),
    amount           NUMERIC(19, 4) NOT NULL,
    posting_date     DATE NOT NULL,
    status           VARCHAR(255) NOT NULL CHECK (status IN ('POSTED')),
    journal_entry_id BIGINT REFERENCES journal_entry (id),
    posted_at        TIMESTAMPTZ NOT NULL
);

CREATE TABLE payment_allocation (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id  BIGINT NOT NULL REFERENCES payment (id) ON DELETE CASCADE,
    document_id BIGINT NOT NULL,
    amount      NUMERIC(19, 4) NOT NULL
);

CREATE INDEX idx_payment_allocation_payment ON payment_allocation (payment_id);
